"""empty message

Revision ID: 9728726be9dd
Revises: 
Create Date: 2024-07-11 18:04:18.355973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9728726be9dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visualization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediastation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('path_to_exec', sa.Text(), nullable=False),
    sa.Column('exhibition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediastation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mediastation_id'], ['mediastation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_association',
    sa.Column('mediacontent_id', sa.Integer(), nullable=True),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.ForeignKeyConstraint(['mediacontent_id'], ['media_content.id'], )
    )
    op.create_table('media_type_association',
    sa.Column('mediacontent_id', sa.Integer(), nullable=True),
    sa.Column('media_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_type.id'], ),
    sa.ForeignKeyConstraint(['mediacontent_id'], ['media_content.id'], )
    )
    op.create_table('visualization_association',
    sa.Column('mediacontent_id', sa.Integer(), nullable=True),
    sa.Column('visualization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mediacontent_id'], ['media_content.id'], ),
    sa.ForeignKeyConstraint(['visualization_id'], ['visualization.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualization_association')
    op.drop_table('media_type_association')
    op.drop_table('interaction_association')
    op.drop_table('media_content')
    op.drop_table('mediastation')
    op.drop_table('visualization')
    op.drop_table('media_type')
    op.drop_table('interaction')
    op.drop_table('exhibition')
    # ### end Alembic commands ###
